language: R
cache: packages
sudo: true
dist: trusty

r:
  - release
  - devel

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

r_packages:
  - devtools
  - covr

r_github_packages:
  - lozalojo/mem
  - tidyverse/ggplot2
  - ropensci/plotly
  
after_success:
  - Rscript -e 'library(covr); codecov()'

before_install:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libssl-dev libcurl4-openssl-dev libmagick++-dev mdbtools unixodbc-dev zip graphicsmagick imagemagick
  - Rscript -e 'update.packages(ask = FALSE)'
